FROM openjdk:17-jdk-alpine
MAINTAINER baeldung.com
COPY target/sampleApplication-0.0.1-SNAPSHOT.jar sampleApplication-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/sampleApplication-0.0.1-SNAPSHOT.jar"]