FROM openjdk:17-jdk-alpine
MAINTAINER baeldung.com
COPY target/weatherApplication-0.0.1-SNAPSHOT.jar weatherApplication-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/sampleApplication-0.0.1-SNAPSHOT.jar"]